pipelines:
  default:
    - parallel:
        - step:
            name: Build and Test Master Data
            image: mcr.microsoft.com/dotnet/sdk:5.0
            caches:
              - dotnetcore
            script:
              - export PROJECT_MD=g4s-master-data-module
              - dotnet restore ./g4s-master-data-module
              - dotnet build $PROJECT_MD
        - step:
            name: Build and Test SPA
            image: node:16.10.0
            caches:
              - node
            script:
              - npm --prefix ./g4s-spa-module install
              - npm --prefix ./g4s-spa-module install @angular/cli -g
              - npm --prefix ./g4s-spa-module run build
            artifacts:
              - node_modules/** # Save modules for next steps
        - step:
            name: Build and Test Feed Master Data
            image: node:16.10.0
            caches:
              - node
            script:
              - npm --prefix ./g4s-feed-module install
              - npm --prefix ./g4s-feed-module run build
            artifacts:
              - node_modules/** # Save modules for next steps