pipelines:
  default:
    - parallel:
        - step:
            name: Build and Test Master Date
            image: mcr.microsoft.com/dotnet/sdk:5.0
            caches:
              - dotnetcore
            script:
              - export PROJECT_MD=g4s-master-data-module
              - dotnet restore ./g4s-master-data-module
              - dotnet build $PROJECT_MD
        - step:
            name: Build and Test SPA
            image: node:12.13.0
            caches:
              - node
            script:
              - npm install
            artifacts:
              - node_modules/** # Save modules for next steps
        - step:
            name: Build
            image: node:12.13.0
            script:
              - ng build