#  Template .NET Core build

#  This template allows you to validate your .NET Core package.
#  The workflow allows running tests and code linting on the default branch.


pipelines:
  default:
    - parallel:
        - step:
            name: Build and Test
            image: microsoft/dotnet:sdk
            caches:
              - dotnetcore
            script:
              - export PROJECT_NAME=Code
              - dotnet restore
              - dotnet build $PROJECT_NAME