#  Template .NET Core build

#  This template allows you to validate your .NET Core package.
#  The workflow allows running tests and code linting on the default branch.


pipelines:
  default:
    - parallel:
        - step:
            name: Build and Test Master Date
            image: mcr.microsoft.com/dotnet/sdk:5.0
            caches:
              - dotnetcore
            script:
              - export PROJECT_MD=g4s-master-data-module
              - dotnet restore ./g4s-master-data-module
              - dotnet build $PROJECT_MD
        - step:
            name: Build andd Test SPA
            image: node:17.2.0
            caches:
              - node
            script: 
               - npm build:prod