pipelines:
  default:
    - parallel:
        - step:
            name: Build and Test Master Data
            image: mcr.microsoft.com/dotnet/sdk:5.0
            caches:
              - dotnetcore
            script:
              - export PROJECT_MD=g4s-master-data-module
              - dotnet restore ./g4s-master-data-module
              - dotnet build $PROJECT_MD
        - step:
            name: Install node
            image: node:12.13.0
            caches:
              - node
            script:
              - export PROJECT_SPA=g4s-spa-module
              - npm install
              - ng build $PROJECT_SPA